export type GuideSource = { label: string; href: string };
export type GuideSection = { title: string; body: string[] };
export type BuyerGuide = {
  slug: string;
  category: "Buyer Guides" | "Due Diligence" | "Seller Guides";
  title: string;
  dek: string;
  intent: string;
  image: string;
  readTime: string;
  sections: GuideSection[];
  checklist: string[];
  questions: string[];
  sources: GuideSource[];
};

const bcTaxSources: GuideSource[] = [
  { label: "BC property transfer tax", href: "https://www2.gov.bc.ca/gov/content/taxes/property-taxes/property-transfer-tax" },
  { label: "BC speculation and vacancy tax", href: "https://www2.gov.bc.ca/gov/content/taxes/speculation-vacancy-tax" },
];

const waterSources: GuideSource[] = [
  { label: "BC water licensing and rights", href: "https://www2.gov.bc.ca/gov/content/environment/air-land-water/water/water-licensing-rights" },
  { label: "BC riparian areas protection", href: "https://www2.gov.bc.ca/gov/content/environment/air-land-water/water/laws-rules/riparian-areas-protection-regulation" },
];

const localSources: GuideSource[] = [
  { label: "City of Nelson", href: "https://www.nelson.ca/" },
  { label: "Village of Kaslo", href: "https://www.kaslo.ca/" },
];

const riskSources: GuideSource[] = [
  { label: "FireSmart BC", href: "https://firesmartbc.ca/" },
  { label: "BC water licensing and rights", href: "https://www2.gov.bc.ca/gov/content/environment/air-land-water/water/water-licensing-rights" },
];

const rdckSource = { label: "Regional District of Central Kootenay", href: "https://www.rdck.ca/" };

const ltsaSources: GuideSource[] = [
  { label: "LTSA title search", href: "https://ltsa.ca/property-owners/how-can-i/search-for-a-title/" },
  { label: "LTSA land title records", href: "https://ltsa.ca/property-owners/about-land-records/" },
];

const permitSources: GuideSource[] = [
  rdckSource,
  { label: "RDCK building permits", href: "https://www.rdck.ca/development-community-sustainability-services/building/" },
  { label: "RDCK mapping and GIS", href: "https://www.rdck.ca/development-community-sustainability-services/mapping/" },
  { label: "Kaslo planning and permits", href: "https://www.kaslo.ca/p/planning-permits" },
  { label: "BC permits and licences", href: "https://www2.gov.bc.ca/gov/content/employment-business/business/managing-a-business/permits-licences" },
];

const riskReviewSources: GuideSource[] = [
  { label: "FireSmart BC", href: "https://firesmartbc.ca/" },
  { label: "BC wildfire map", href: "https://wildfiresituation.nrs.gov.bc.ca/map" },
  { label: "BC flood maps", href: "https://www2.gov.bc.ca/gov/content/environment/air-land-water/water/drought-flooding-dikes-dams/integrated-flood-hazard-management/flood-hazard-land-use-management/floodplain-mapping" },
  { label: "BC climate and hazard data", href: "https://climatedata.ca/" },
];

const buyerProcessSources: GuideSource[] = [
  { label: "BC home buying and selling", href: "https://www2.gov.bc.ca/gov/content/housing-tenancy/buying-selling" },
  { label: "BC Financial Services Authority", href: "https://www.bcfsa.ca/" },
  { label: "CMHC homebuying", href: "https://www.cmhc-schl.gc.ca/consumers/home-buying" },
];

const inspectionSources: GuideSource[] = [
  { label: "Consumer Protection BC home inspectors", href: "https://www.consumerprotectionbc.ca/consumer-help/home-inspectors/" },
  { label: "BC water quality", href: "https://www2.gov.bc.ca/gov/content/environment/air-land-water/water/water-quality" },
  { label: "BC onsite sewerage", href: "https://www2.gov.bc.ca/gov/content/environment/waste-management/sewage/onsite-sewage-systems" },
];

const alrSources: GuideSource[] = [
  { label: "Agricultural Land Commission", href: "https://www.alc.gov.bc.ca/" },
  { label: "Agricultural Land Reserve maps", href: "https://www.alc.gov.bc.ca/alr-maps/" },
];

const shortTermRentalSources: GuideSource[] = [
  { label: "BC short-term rental rules", href: "https://www2.gov.bc.ca/gov/content/housing-tenancy/short-term-rentals" },
  { label: "City of Nelson short-term rentals", href: "https://www.nelson.ca/" },
  rdckSource,
];

export const buyerGuides: BuyerGuide[] = [
  {
    slug: "buying-kootenay-lake-waterfront-property",
    category: "Buyer Guides",
    title: "Buying Waterfront Property on Kootenay Lake",
    dek: "A practical guide to shoreline access, water rights, docks, services, and the questions to settle before a showing.",
    intent: "For buyers comparing lakefront, lake access, and view properties around Kootenay Lake.",
    image: "/generated/guide-headers/buying-kootenay-lake-waterfront-property.webp",
    readTime: "7 min read",
    sections: [
      { title: "Start with what is actually being sold", body: ["Waterfront can mean fee simple shoreline, shared access, community waterfront, a nearby beach, or a view over the lake. Those are not interchangeable. Confirm what rights are included on title, what is shared, and what depends on association, strata, easement, or licence terms.", "In British Columbia, water itself is owned by the Crown. If a property depends on surface water or groundwater use beyond basic domestic purposes, the right to use that water may require provincial authorization."] },
      { title: "The shoreline needs careful review", body: ["A waterfront purchase should include careful review of riparian areas, flood risk, erosion, septic location, slope, road access, insurance, and any existing dock or foreshore structure.", "If the listing mentions a dock, moorage, shared waterfront, creek, or lake access, ask for documents early. The right time to discover uncertainty is before offer strategy, not after acceptance."] },
      { title: "Use the showing to test daily life", body: ["A showing should answer more than whether the view is beautiful. Test privacy, afternoon sun, road noise, stairs to the water, winter access, cell service, internet, storage, guest parking, and how the property would actually be used in each season."] },
    ],
    checklist: ["Confirm title, strata, easements, and shared waterfront rights", "Ask about water source, septic, dock status, and foreshore permissions", "Review flood, erosion, wildfire, access, and insurance questions", "Compare lakefront, lake access, and lake view pricing separately"],
    questions: ["What exact waterfront rights transfer with the property?", "Is the dock, beach, path, or access point private, shared, licensed, or informal?", "What should be verified with the lawyer, inspector, insurer, and local government before writing?"],
    sources: [...waterSources, ...bcTaxSources],
  },
  {
    slug: "kootenay-lake-waterfront-vs-lake-access",
    category: "Buyer Guides",
    title: "Kootenay Lake Waterfront vs. Lake Access",
    dek: "The difference between owning shoreline, sharing access, and enjoying a lake view can change price, use, privacy, and risk.",
    intent: "For buyers who want the lake life but need to understand what the listing language really means.",
    image: "/generated/guide-headers/kootenay-lake-waterfront-vs-lake-access.webp",
    readTime: "5 min read",
    sections: [
      { title: "The rights are different", body: ["Waterfront usually suggests a direct relationship with the shoreline, but the exact legal interest still needs review. Lake access may mean shared land, a community beach, an easement, a strata amenity, or proximity. Lake view may carry daily-life value without any right to use the shoreline.", "The correct question is not whether the property feels close to the lake. The correct question is what use, access, and obligations are legally attached to the property."] },
      { title: "Price should follow rights and usability", body: ["A property with clean, usable shoreline can carry a different price than a home with a view or a shared access path. The comparison set should reflect the actual right being purchased, not just the lake in the photos.", "For buyers, privacy and ease of use matter. A shared waterfront area may be excellent, but it is not the same buyer experience as private shoreline."] },
      { title: "Documentation beats assumptions", body: ["Ask for maps, title documents, strata or association material, water and septic information, and any relevant licences or agreements. If the property relies on a shared structure or access route, understand maintenance, cost, governance, and practical availability."] },
    ],
    checklist: ["Separate waterfront, lake access, and lake view in your shortlist", "Verify legal access, not just physical access", "Ask who maintains shared roads, paths, docks, or beach areas", "Compare privacy, slope, parking, and seasonal use"],
    questions: ["What exactly can the owner use?", "Who else can use it?", "What documents prove the right?"],
    sources: waterSources,
  },
  {
    slug: "moving-to-nelson-bc",
    category: "Buyer Guides",
    title: "Moving to Nelson, BC",
    dek: "A relocation guide for buyers comparing walkability, services, seasons, mountain access, and the reality behind the postcard.",
    intent: "For buyers coming from Vancouver, Calgary, Ontario, the United States, or elsewhere in BC.",
    image: "/generated/guide-headers/moving-to-nelson-bc.webp",
    readTime: "6 min read",
    sections: [
      { title: "Nelson is a daily-life choice first", body: ["Nelson is known for its historic downtown, mountain setting, arts culture, and access to Kootenay Lake. For buyers, the real decision is not simply Nelson or not Nelson. It is walkable town life, hillside views, North Shore privacy, rural acreage, or lake access near services.", "A strong relocation search starts by deciding how daily life should work before looking at individual homes."] },
      { title: "Tour the routine", body: ["A useful scouting trip includes grocery routes, schools if relevant, winter driving, healthcare access, recreation habits, commute patterns, internet needs, and how guests will arrive. Beautiful homes can still be the wrong fit if the daily rhythm is wrong."] },
      { title: "Match the property type to the season", body: ["In the Kootenays, winter access, slope, snow storage, heating systems, road maintenance, and sun deserve attention. Summer viewings can hide winter tradeoffs."] },
    ],
    checklist: ["Decide town, lake, acreage, or ski rhythm first", "Tour daily services and winter routes", "Confirm internet, heat, access, parking, and maintenance", "Use a local showing plan instead of browsing randomly"],
    questions: ["Which neighbourhoods fit the life I want?", "What will winter change about this property?", "What local tradeoffs should I understand before offering?"],
    sources: localSources,
  },
  {
    slug: "moving-to-kaslo-bc",
    category: "Buyer Guides",
    title: "Moving to Kaslo, BC",
    dek: "What buyers should understand about Kaslo, Kootenay Lake, small-town services, access, and privacy.",
    intent: "For buyers considering Kaslo, North Kootenay Lake, or a quieter lake and mountain setting.",
    image: "/generated/guide-headers/moving-to-kaslo-bc.webp",
    readTime: "5 min read",
    sections: [
      { title: "Kaslo rewards buyers who want quiet", body: ["The Village of Kaslo describes itself as a picturesque village in the West Kootenay region on the west shore of Kootenay Lake. For real estate buyers, that setting can offer lake, mountain, heritage, and privacy appeal, but it should be evaluated with practical questions about services and access."] },
      { title: "Distance is part of the value equation", body: ["Some buyers want the quieter pace. Others underestimate how often they need larger-town services, flights, trades, medical appointments, or winter travel. A showing should include the roads and routines around the property, not only the rooms inside it."] },
      { title: "Lake life needs documentation", body: ["If a Kaslo-area property includes lake access, community waterfront, creek frontage, strata elements, or rural services, verify the documents. Local knowledge helps narrow questions, but legal and technical details still belong with lawyers, inspectors, insurers, and local authorities."] },
    ],
    checklist: ["Test distance to services and regular routes", "Confirm winter access and road maintenance", "Review lake, creek, water, septic, and strata details", "Separate quiet living value from resale practicality"],
    questions: ["How often will I need Nelson, Castlegar, or larger services?", "What is maintained privately, by strata, or by local government?", "What should be checked before committing to a rural lake life?"],
    sources: [{ label: "Village of Kaslo", href: "https://www.kaslo.ca/" }, ...waterSources],
  },
  {
    slug: "nelson-vs-kaslo-vs-balfour",
    category: "Buyer Guides",
    title: "Nelson vs. Kaslo vs. Balfour",
    dek: "A practical comparison for buyers choosing between town energy, lake access, ferry rhythm, privacy, and small-community pace.",
    intent: "For buyers narrowing the Kootenay life before booking showings.",
    image: "/generated/guide-headers/nelson-vs-kaslo-vs-balfour.webp",
    readTime: "6 min read",
    sections: [
      { title: "Choose the life before the address", body: ["Nelson often appeals to buyers who want heritage, restaurants, services, culture, and walkability close to Kootenay Lake. Kaslo often appeals to buyers seeking quieter village life on the lake. Balfour can suit buyers who want lake access, ferry connection, and a more rural rhythm near the West Arm and main lake."] },
      { title: "The best choice depends on daily use", body: ["A second-home buyer, a full-time family, a retiree, and a remote worker can all look at the same map and need different answers. The right comparison includes services, road habits, internet, winter, guests, maintenance, recreation, and resale."] },
      { title: "Compare tradeoffs in person", body: ["Do not compare only square footage and price. Compare the lived pattern: where you buy groceries, how often you cross the ferry, how guests arrive, how winter affects the driveway, and how much privacy you actually want."] },
    ],
    checklist: ["Pick your non-negotiable way of life first", "Compare road rhythm and services", "Test lake, town, and rural tradeoffs in one showing day", "Ask which compromises buyers regret later"],
    questions: ["Do I want walkability, quiet, ferry access, or privacy most?", "Which area fits full-time living versus second-home use?", "What would be hard to resell if my needs change?"],
    sources: localSources,
  },
  {
    slug: "rural-luxury-property-due-diligence-bc",
    category: "Due Diligence",
    title: "How to Evaluate a Rural Property in BC",
    dek: "A clear review framework for buyers considering acreage, lake access, privacy, outbuildings, wells, septic, and rural systems.",
    intent: "For buyers who need more than a beautiful showing before writing a serious offer.",
    image: "/generated/guide-headers/rural-luxury-property-due-diligence-bc.webp",
    readTime: "8 min read",
    sections: [
      { title: "Rural property is systems plus setting", body: ["The appeal is land, views, workshops, guest space, water, forest, and quiet. The risk is that every one of those benefits can carry a system, cost, restriction, or maintenance question. A careful buyer evaluates both the romance and the infrastructure."] },
      { title: "Confirm what professionals must verify", body: ["A real estate professional can help frame questions, but lawyers, inspectors, insurers, surveyors, septic professionals, well specialists, and local government staff may all be needed depending on the property. The more unique the property, the less useful generic assumptions become."] },
      { title: "Do not let photos outrun documents", body: ["Before writing or removing conditions, understand title, zoning, access, water, septic, heating, insurance, wildfire risk, building permits where relevant, boundaries, and any shared road or easement obligations."] },
    ],
    checklist: ["Review title, access, easements, and zoning", "Inspect water, septic, heat, roof, drainage, and outbuildings", "Ask about wildfire mitigation and insurance", "Confirm what the current owner maintains privately"],
    questions: ["What system failure would be expensive here?", "What document should I review before offering?", "Who needs to inspect this property besides a general home inspector?"],
    sources: [...waterSources, ...riskSources],
  },
  {
    slug: "buying-acreage-in-the-kootenays",
    category: "Due Diligence",
    title: "Buying Acreage in the Kootenays",
    dek: "How to think about usable land, slope, access, water, zoning, outbuildings, privacy, and long-term maintenance.",
    intent: "For buyers comparing rural acreage near Nelson, Blewett, Slocan Valley, Pass Creek, and Kootenay Lake communities.",
    image: "/generated/guide-headers/buying-acreage-in-the-kootenays.webp",
    readTime: "6 min read",
    sections: [
      { title: "Acreage is not only the number of acres", body: ["Usable land matters more than the headline number. Slope, access, sun, drainage, forest, ALR status where applicable, zoning, services, and building sites can change how the property lives and what it may support."] },
      { title: "Privacy has a maintenance cost", body: ["Long driveways, private roads, snow clearing, drainage, tree work, fire mitigation, wells, septic, and outbuildings can be exactly what a buyer wants. They are also responsibilities to price into ownership."] },
      { title: "Plan around future use", body: ["If you imagine a guest cabin, shop, studio, garden, rental, subdivision, or major renovation, verify rules early. Rural flexibility depends on zoning, servicing, access, environmental constraints, and approvals."] },
    ],
    checklist: ["Walk the land, not just the house", "Review zoning and permitted uses", "Ask about road, snow, drainage, water, and septic", "Price maintenance into the ownership plan"],
    questions: ["How much land is actually usable?", "What future use is legally and practically possible?", "What would a local owner check before buying this acreage?"],
    sources: [...riskSources, rdckSource],
  },
  {
    slug: "winter-access-year-round-living-kootenays",
    category: "Due Diligence",
    title: "Winter Access and Year-Round Living in the Kootenays",
    dek: "The winter questions that matter for rural homes, lake properties, steep drives, second homes, and relocation buyers.",
    intent: "For buyers who toured in summer and need to understand the property in February.",
    image: "/generated/guide-headers/winter-access-year-round-living-kootenays.webp",
    readTime: "5 min read",
    sections: [
      { title: "Winter changes the property test", body: ["A driveway, road, roofline, heating system, lake access path, or rural service distance can feel simple in July and very different in winter. Year-round living requires a clear look at snow storage, plowing, grade, sun, backup heat, and who maintains the access."] },
      { title: "Second homes need a caretaker plan", body: ["If the property will sit empty, ask who checks heat, snow, water, alarms, access, and storm damage. A beautiful second home becomes stressful when nobody local is responsible for small problems before they become expensive ones."] },
      { title: "Insurance and wildfire still matter", body: ["Winter access is one side of rural ownership. Wildfire mitigation, defensible space, roof and gutter maintenance, and insurance availability should also be part of the annual ownership plan."] },
    ],
    checklist: ["Ask who maintains the road and driveway", "Confirm heat source, backup systems, and utility reliability", "Plan for snow storage, access, and caretaker coverage", "Review wildfire mitigation and insurance early"],
    questions: ["Would I buy this property if I toured it in winter?", "Who keeps the property safe when I am away?", "What seasonal cost is not obvious in the listing?"],
    sources: riskSources,
  },
  {
    slug: "septic-water-access-insurance-rural-bc",
    category: "Due Diligence",
    title: "Septic, Water, Access, and Insurance in Rural BC",
    dek: "Four quiet issues that can decide whether a rural or waterfront property is easy to own or expensive to correct.",
    intent: "For buyers who want a focused checklist before removing conditions.",
    image: "/generated/guide-headers/septic-water-access-insurance-rural-bc.webp",
    readTime: "7 min read",
    sections: [
      { title: "Water deserves early attention", body: ["In BC, water use is governed provincially. Domestic groundwater use is treated differently from non-domestic groundwater use, and non-domestic use can require a water licence. Buyers should understand the property water source, records, quality, quantity, treatment, and any licences or shared systems."] },
      { title: "Septic is not cosmetic", body: ["A rural septic system should be treated as core infrastructure. Buyers should ask for available records, service history, age, capacity, location, and inspection advice from a licensed professional. The system must suit the home, use, and site conditions."] },
      { title: "Access and insurance are ownership issues", body: ["Shared roads, private roads, steep drives, bridges, wildfire risk, and distance from services can affect cost, maintenance, and insurance. These are not reasons to avoid rural property. They are reasons to investigate properly."] },
    ],
    checklist: ["Identify the water source and any licences or records", "Inspect septic with licensed advice", "Confirm legal and practical access", "Speak with insurance early in the process"],
    questions: ["What system would be hardest to replace?", "What records are available?", "What should my insurer know before I write?"],
    sources: [...waterSources, ...riskSources],
  },
  {
    slug: "access-easements-shared-roads-bc",
    category: "Due Diligence",
    title: "Access Easements and Shared Roads in Rural BC",
    dek: "Why legal access, practical access, road maintenance, and neighbour agreements should be reviewed before a rural purchase.",
    intent: "For buyers considering acreages, lake homes, remote properties, or shared waterfront communities.",
    image: "/generated/guide-headers/access-easements-shared-roads-bc.webp",
    readTime: "5 min read",
    sections: [
      { title: "A driveway is not the same as legal access", body: ["If a property depends on crossing another parcel, using a shared road, or maintaining a private route, confirm the legal basis and maintenance expectations. The map, title documents, easements, road agreements, and local knowledge all matter."] },
      { title: "Maintenance should not be vague", body: ["Who plows, grades, drains, repairs, insures, and pays for the road? If the answer is informal, understand the risk. Informal arrangements can work for years, but buyers should know what they are inheriting."] },
      { title: "Access affects financing, insurance, and resale", body: ["A property with unclear access can create friction beyond daily inconvenience. It may affect lender comfort, insurance, future buyers, and long-term value. This is a lawyer question, not a handshake question."] },
    ],
    checklist: ["Review title, easements, plans, and road agreements", "Ask who maintains and pays for access", "Confirm emergency, winter, and guest access", "Treat unclear access as a pre-offer issue"],
    questions: ["Is the access legal, practical, and year-round?", "Who is responsible for maintenance?", "Would the same access story satisfy my lender and insurer?"],
    sources: [{ label: "Land Title and Survey Authority of BC", href: "https://ltsa.ca/" }, rdckSource],
  },
  {
    slug: "luxury-home-marketing-kootenays",
    category: "Seller Guides",
    title: "How Important Homes Should Be Marketed in the Kootenays",
    dek: "Why unique rural, lake, view, and long-held properties need more than an MLS upload and attractive photography.",
    intent: "For sellers deciding how an important Kootenay property should be prepared before listing.",
    image: "/generated/guide-headers/luxury-home-marketing-kootenays.webp",
    readTime: "6 min read",
    sections: [
      { title: "Strong marketing starts before listing", body: ["The strongest sale plans clarify the likely buyer, the property story, the strongest objections, the showing plan, and the assets needed to make the home understandable from a distance. For rural and waterfront homes, the buyer may not be local. The page has to do more work before the showing."] },
      { title: "The property needs to be explained", body: ["Drone, video, photography, room information, area context, and clear copy should reduce uncertainty. Overstated adjectives do not help if the buyer still cannot understand access, daily life, privacy, or systems."] },
      { title: "Serious attention beats empty traffic", body: ["A seller does not need every buyer. They need the right buyer to understand the property, believe the value, and take the next step with seriousness. Marketing should filter as much as it attracts."] },
    ],
    checklist: ["Define the buyer before writing the listing", "Build visual assets that explain the property", "Answer objections before showings", "Use the listing page as a serious presentation tool"],
    questions: ["Who is the right buyer and what will they worry about?", "What must be shown visually to justify value?", "What should be private, public, or shown only to serious buyers?"],
    sources: [{ label: "Luke Mori listings", href: "/listings" }, { label: "Luke Mori seller guidance", href: "/sellers" }],
  },
  {
    slug: "preparing-waterfront-home-for-market-kootenays",
    category: "Seller Guides",
    title: "Preparing a Waterfront Home for Market in the Kootenays",
    dek: "A seller guide for presenting shoreline, views, docks, access, systems, and daily life without overpromising.",
    intent: "For owners of lakefront, lake access, creekside, or view properties preparing to sell.",
    image: "/generated/guide-headers/preparing-waterfront-home-for-market-kootenays.webp",
    readTime: "6 min read",
    sections: [
      { title: "Prepare documents before attention", body: ["Waterfront buyers ask sharper questions. Before listing, gather what you can about title, access, dock or foreshore matters, strata or community waterfront rights, septic, water, maintenance, insurance, and upgrades. The goal is not to overwhelm buyers. It is to reduce uncertainty for serious ones."] },
      { title: "Show daily life with restraint", body: ["The best waterfront marketing shows approach, privacy, shoreline usability, outdoor rooms, views, guest flow, and daily life in multiple seasons where possible. It should not imply rights or uses that are not documented."] },
      { title: "Price the rights, not only the view", body: ["A direct waterfront property, a shared-access property, and a lake-view property may attract different buyers and deserve different comparable sets. Sale strategy should make that distinction clear."] },
    ],
    checklist: ["Gather documents that support access, waterfront use, and systems", "Prepare shoreline, decks, paths, windows, and outdoor spaces", "Clarify what is private, shared, licensed, or informal", "Price against the correct waterfront category"],
    questions: ["What will buyers ask about water, access, and systems?", "What can be documented before listing?", "What claim should be avoided because it cannot be proven?"],
    sources: waterSources,
  },
  {
    slug: "pricing-unique-kootenay-property",
    category: "Seller Guides",
    title: "How to Price a Unique Kootenay Property",
    dek: "Why waterfront, acreage, view, and legacy homes need a pricing strategy beyond ordinary comparables.",
    intent: "For sellers preparing a property that is hard to compare cleanly against recent sales.",
    image: "/generated/guide-headers/pricing-unique-kootenay-property.webp",
    readTime: "6 min read",
    sections: [
      { title: "Unique homes need a clearer pricing argument", body: ["A distinctive property can be valuable because of privacy, lake access, views, acreage, architecture, guest capacity, or rarity. The challenge is proving that value without assuming every feature adds dollar-for-dollar value.", "Pricing should separate what buyers can verify from what the seller feels. The right number usually comes from comparable sales, current competition, replacement difficulty, buyer depth, and how clearly the property can be explained."] },
      { title: "Rare does not mean unlimited demand", body: ["A rare property can still sit if the price outruns the buyer pool. The sale strategy should identify who is most likely to care, what they will compare against, and what objections must be solved before the first showing."] },
      { title: "Presentation affects pricing confidence", body: ["Strong photography, video, property pages, room clarity, documents, and area context help buyers understand why the property deserves attention. Weak presentation makes even the right price feel uncertain." ] },
    ],
    checklist: ["Separate emotional value from market evidence", "Compare against active competition and closed sales", "Identify buyer objections before listing", "Prepare the evidence that supports the price"],
    questions: ["Which features are truly scarce?", "What would the best buyer compare this against?", "What evidence supports the asking range?"],
    sources: [{ label: "Luke Mori seller guidance", href: "/sellers" }, { label: "Luke Mori sold listings", href: "/listings/sold" }],
  },
  {
    slug: "questions-before-hiring-luxury-listing-agent",
    category: "Seller Guides",
    title: "What Sellers Should Ask Before Hiring a Listing Agent",
    dek: "The questions that reveal whether an agent can price, prepare, market, screen, and negotiate an important property properly.",
    intent: "For sellers interviewing agents before listing a waterfront, acreage, or unique home.",
    image: "/generated/guide-headers/questions-before-hiring-luxury-listing-agent.webp",
    readTime: "6 min read",
    sections: [
      { title: "Ask how the price will be defended", body: ["A listing agent should be able to explain the pricing method, the comparable set, the current competition, and the risks of both overpricing and underpricing. A confident number without a clear argument is not strategy." ] },
      { title: "Ask how the property will be understood", body: ["For unique Kootenay homes, marketing should explain the property, not simply decorate it. Ask about photography, video, copy, floor and room information, local context, buyer objections, and how inquiries will be screened." ] },
      { title: "Ask what happens after listing", body: ["The listing is only the start. Sellers should understand feedback loops, showing quality, privacy, negotiation posture, offer handling, and when the strategy should change if the market does not respond." ] },
    ],
    checklist: ["Ask for the pricing argument", "Review the marketing plan before signing", "Understand buyer screening and showing process", "Clarify feedback, privacy, and negotiation strategy"],
    questions: ["How will you explain this property to an out-of-area buyer?", "What objections do you expect?", "How will you protect privacy while still creating demand?"],
    sources: [{ label: "Luke Mori about", href: "/about" }, { label: "Luke Mori testimonials", href: "/testimonials" }],
  },
  {
    slug: "preparing-acreage-property-for-market-kootenays",
    category: "Seller Guides",
    title: "Preparing an Acreage Property for Market in the Kootenays",
    dek: "How to prepare land, outbuildings, access, documents, systems, and photography before listing an acreage property.",
    intent: "For acreage owners who want buyers to understand the land instead of only touring the house.",
    image: "/generated/guide-headers/preparing-acreage-property-for-market-kootenays.webp",
    readTime: "6 min read",
    sections: [
      { title: "Make the usable land obvious", body: ["Acreage buyers need to understand slope, access, sun, drainage, gardens, outbuildings, parking, guest areas, privacy, and future use. The showing should not leave them guessing which parts of the land are practical." ] },
      { title: "Prepare the systems story", body: ["Water, septic, road maintenance, snow clearing, heat, outbuildings, drainage, and wildfire mitigation can all affect confidence. Gather service records, maps, permits where available, and clear explanations before listing." ] },
      { title: "Do not over-stage the wrong things", body: ["Acreage preparation is less about making everything look suburban and more about making the property legible. Clear paths, tidy utility areas, accessible outbuildings, visible boundaries, and honest maintenance details matter." ] },
    ],
    checklist: ["Clear access routes and key land features", "Gather water, septic, road, and outbuilding records", "Prepare maps or notes for boundaries and usable areas", "Address wildfire, drainage, and maintenance questions early"],
    questions: ["What parts of the acreage are genuinely usable?", "What systems will buyers ask about first?", "What should be photographed, mapped, or explained before listing?"],
    sources: [rdckSource, ...riskSources],
  },
  {
    slug: "buying-second-home-kootenays",
    category: "Buyer Guides",
    title: "Buying a Second Home in the Kootenays",
    dek: "A practical guide to caretaker plans, winterization, insurance, travel rhythm, guests, and remote ownership.",
    intent: "For buyers considering a part-time home, family retreat, or long-term relocation foothold.",
    image: "/generated/guide-headers/buying-second-home-kootenays.webp",
    readTime: "6 min read",
    sections: [
      { title: "Second homes need an ownership plan", body: ["The best second-home purchase is not only beautiful when you arrive. It is manageable when you are not there. Buyers should plan for heat, water, snow, alarms, insurance, storm checks, landscaping, guest access, and local service relationships." ] },
      { title: "Be honest about travel rhythm", body: ["A property that feels perfect on a holiday weekend may be harder to use if the drive, flights, ferry timing, winter access, or maintenance demands are heavier than expected. The right home matches the way you will actually visit." ] },
      { title: "Check rules before assuming rental or guest use", body: ["If rental income, guest stays, caretaker suites, strata rules, or future renovations matter, verify the rules before buying. Local government, strata, insurance, lender, tax, and legal advice may all be relevant." ] },
    ],
    checklist: ["Build a caretaker and maintenance plan", "Confirm winterization and access", "Review insurance, taxes, strata, and rental assumptions", "Test travel time and guest logistics"],
    questions: ["Who watches the property when I am away?", "How often will I realistically use it?", "What rules limit rental, guests, renovations, or future use?"],
    sources: [...bcTaxSources, ...riskSources],
  },
  {
    slug: "out-of-province-buyers-buying-in-bc",
    category: "Buyer Guides",
    title: "Out-of-Province Buyers Buying in BC",
    dek: "What Alberta, Ontario, U.S., and other non-local buyers should know before purchasing in the Kootenays.",
    intent: "For buyers who need a clean BC process before they book travel or write remotely.",
    image: "/generated/guide-headers/out-of-province-buyers-buying-in-bc.webp",
    readTime: "7 min read",
    sections: [
      { title: "BC costs and rules need early attention", body: ["Buyers should understand property transfer tax, annual property taxes, possible speculation and vacancy tax obligations in designated areas, financing timing, insurance, legal closing process, and any residency or foreign-buyer rules that may apply at the time of purchase.", "Rules change. Treat online guidance as a starting point, then confirm with a BC lawyer or notary, tax advisor, lender, and insurer." ] },
      { title: "Remote review must be organized", body: ["Out-of-area buyers should decide what can be reviewed remotely, what requires an in-person showing, and what needs local professional inspection. Video can help, but it should not replace technical review of water, septic, access, strata, insurance, and title questions." ] },
      { title: "Local context prevents expensive surprises", body: ["The biggest surprises are often practical: winter roads, service distance, trades availability, ferry rhythm, internet, wildfire risk, and how daily life differs from the buyer's current market." ] },
    ],
    checklist: ["Confirm BC taxes and closing process", "Line up lawyer or notary, lender, insurer, and inspector", "Verify property-specific systems before removing conditions", "Plan a showing route that tests daily life and access"],
    questions: ["What BC-specific cost am I missing?", "What must be seen in person?", "Which local tradeoffs would not be obvious from another province or country?"],
    sources: [...bcTaxSources, { label: "BC Financial Services Authority", href: "https://www.bcfsa.ca/" }],
  },
  {
    slug: "strata-bare-land-strata-rural-bc",
    category: "Due Diligence",
    title: "Understanding Strata and Bare Land Strata in Rural BC",
    dek: "How strata, bare land strata, shared roads, common property, fees, bylaws, and documents can affect rural ownership.",
    intent: "For buyers considering strata homes, shared waterfront communities, bare land strata, or rural subdivisions.",
    image: "/generated/guide-headers/strata-bare-land-strata-rural-bc.webp",
    readTime: "7 min read",
    sections: [
      { title: "Strata can include more than condos", body: ["BC's strata housing information notes that strata can include condos, townhouses, duplexes, and even single family homes in bare land strata corporations. In strata housing, owners own individual strata lots and together own common property and common assets as a strata corporation." ] },
      { title: "Shared amenities need document review", body: ["In rural settings, strata or bare land strata may involve shared roads, septic, water, waterfront, trails, buildings, landscaping, or other common assets. Buyers should review bylaws, rules, fees, minutes, financials, insurance, depreciation reports where available, and responsibility for maintenance." ] },
      { title: "Shared ownership can work well if the governance fits", body: ["Shared ownership can provide access and convenience, but it also creates obligations. The question is whether the rules, costs, neighbours, and maintenance structure fit the way you want to use the property." ] },
    ],
    checklist: ["Review strata plan, bylaws, rules, fees, minutes, and financials", "Confirm what is common property or a common asset", "Ask about shared roads, waterfront, water, septic, and insurance", "Have legal advice review the documents before removing conditions"],
    questions: ["What do I own individually and what is shared?", "Who decides maintenance and cost?", "Do the bylaws fit my intended use?"],
    sources: [{ label: "BC strata housing", href: "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing" }, rdckSource],
  },
  {
    slug: "renovating-building-rural-kootenay-property",
    category: "Due Diligence",
    title: "Renovating or Building on Rural Kootenay Property",
    dek: "What buyers should verify before assuming they can renovate, add buildings, expand septic, or build on rural land.",
    intent: "For buyers who see future potential in land, outbuildings, guest space, studios, or major renovations.",
    image: "/generated/guide-headers/renovating-building-rural-kootenay-property.webp",
    readTime: "7 min read",
    sections: [
      { title: "Potential needs permission", body: ["A property may feel like it has room for a shop, suite, guest cabin, studio, or major renovation, but future use depends on zoning, building permits, access, servicing, septic capacity, water, environmental constraints, and local bylaws." ] },
      { title: "RDCK building permits and inspections matter", body: ["The RDCK building department says it issues building and plumbing permits and conducts inspections across its geographic area, with some municipalities handled directly by those municipalities. Its public information notes that complete applications help processing and that timelines depend on workload." ] },
      { title: "Trades, access, and seasonality affect feasibility", body: ["Rural projects can be shaped by contractor availability, winter access, delivery routes, slope, drainage, utilities, wildfire mitigation, and site preparation. Feasible on paper does not always mean easy or fast in practice." ] },
    ],
    checklist: ["Confirm zoning and permitted uses", "Ask the correct local authority about permits", "Review septic, water, access, slope, and environmental constraints", "Price trades, timing, and seasonal access before assuming value"],
    questions: ["Is my intended use permitted?", "Which permits or inspections would be required?", "What site condition could make the project harder than expected?"],
    sources: [rdckSource, { label: "BC permits and licences", href: "https://www2.gov.bc.ca/gov/content/employment-business/business/managing-a-business/permits-licences" }, ...riskSources],
  },
  {
    slug: "offer-strategy-luxury-homes-nelson-kootenay-lake",
    category: "Buyer Guides",
    title: "Offer Strategy for Important Homes in Nelson and Kootenay Lake",
    dek: "How serious buyers should think about conditions, timing, evidence, negotiation, and emotional discipline on unique properties.",
    intent: "For buyers preparing to write on an important home where the comparison set is not simple.",
    image: "/generated/guide-headers/offer-strategy-luxury-homes-nelson-kootenay-lake.webp",
    readTime: "6 min read",
    sections: [
      { title: "The right offer starts before the form", body: ["A strong offer is built from preparation: financing clarity, legal advice, inspection plan, understanding of the seller's timing, and a clear view of what must be verified. The paperwork should reflect decisions already made, not create them in a rush." ] },
      { title: "Conditions should match the property", body: ["A rural or waterfront property may require different review than an ordinary urban home. Water, septic, access, strata, title, insurance, zoning, wildfire, and building questions can all shape the condition strategy." ] },
      { title: "Emotional discipline protects value", body: ["Unique properties can create urgency because there may be no identical replacement. That does not mean every price or term is justified. A good offer strategy separates what you love from what the market, documents, and risk profile support." ] },
    ],
    checklist: ["Clarify financing and deposit position", "Identify must-verify conditions before writing", "Understand seller timing and motivation where possible", "Decide walk-away terms before emotion rises"],
    questions: ["What do I need verified before I can own this confidently?", "Where is the seller likely flexible?", "What price is supported by evidence, not adrenaline?"],
    sources: [{ label: "BC Financial Services Authority", href: "https://www.bcfsa.ca/" }, ...bcTaxSources],
  },
  {
    slug: "bc-property-transfer-tax-closing-costs-kootenay-buyers",
    category: "Buyer Guides",
    title: "BC Property Transfer Tax and Closing Costs for Kootenay Buyers",
    dek: "A plain guide to property transfer tax, deposits, legal fees, adjustments, GST questions, and the costs buyers should plan for before writing.",
    intent: "For buyers who want the full purchase picture before falling in love with a Kootenay home.",
    image: "/generated/guide-headers/bc-property-transfer-tax-closing-costs-kootenay-buyers.webp",
    readTime: "7 min read",
    sections: [
      { title: "The price is not the full cash need", body: ["A purchase price is only one part of the money conversation. Buyers should also plan for deposit timing, property transfer tax, legal fees, title searches, inspections, insurance, lender requirements, moving costs, utility adjustments, and any property-specific review that needs a professional.", "For higher-value homes, the property transfer tax can be material. It should be estimated before offer strategy, not discovered after the property feels like the one."] },
      { title: "Taxes and exemptions need current advice", body: ["BC property transfer tax rules, exemptions, GST questions, and speculation or vacancy tax questions can change or depend on buyer status, property type, intended use, and location. Use official provincial sources and confirm with a lawyer or tax professional before relying on a number."] },
      { title: "Closing costs affect offer confidence", body: ["A buyer who understands the full closing picture can write with more confidence and fewer surprises. This matters most on waterfront, acreage, second homes, and unique properties where inspections, insurance, title, water, septic, or zoning review may add steps."] },
    ],
    checklist: ["Estimate property transfer tax before writing", "Confirm deposit timing and available funds", "Budget for legal, inspection, insurance, title, and adjustment costs", "Ask whether GST, exemptions, or tax advice may apply"],
    questions: ["What costs are due before closing and on closing day?", "Could GST, property transfer tax, or speculation tax affect this purchase?", "Which costs should be confirmed by my lawyer, lender, accountant, or insurer?"],
    sources: [...bcTaxSources, ...ltsaSources, { label: "BC home buyer information", href: "https://www2.gov.bc.ca/gov/content/housing-tenancy/buying-selling" }],
  },
  {
    slug: "short-term-rental-rules-second-homes-bc",
    category: "Due Diligence",
    title: "Short-Term Rental Rules for Second Homes in BC",
    dek: "What second-home buyers should understand before assuming a Kootenay property can be rented nightly or seasonally.",
    intent: "For second-home buyers, waterfront owners, and investors who want occasional rental income without guessing at the rules.",
    image: "/generated/guide-headers/short-term-rental-rules-second-homes-bc.webp",
    readTime: "6 min read",
    sections: [
      { title: "Do not assume rental use is allowed", body: ["A beautiful second home is not automatically a short-term rental. Provincial rules, municipal rules, regional district requirements, strata bylaws, insurance, financing, tax treatment, and platform obligations can all affect what is allowed.", "If rental income is part of the ownership plan, confirm the rules before writing or removing conditions."] },
      { title: "Location changes the answer", body: ["A home inside a municipality, a rural RDCK area, a strata property, or a lake community may face different rules and practical limits. The correct question is not whether similar homes are online. The correct question is whether this property can legally and practically be used the way you intend."] },
      { title: "Income plans need conservative math", body: ["Even where rental use is possible, buyers should think about management, cleaning, caretaker support, winter access, guest parking, neighbours, insurance, repairs, taxes, and periods when the property may not be rentable."] },
    ],
    checklist: ["Check provincial short-term rental rules", "Confirm local government and strata rules", "Ask your insurer and lender about rental use", "Build conservative numbers for management, cleaning, repairs, and vacancy"],
    questions: ["Is short-term rental use legal for this property?", "Who enforces the rules here?", "Would rental use change insurance, financing, taxes, or neighbours' expectations?"],
    sources: shortTermRentalSources,
  },
  {
    slug: "does-speculation-tax-apply-nelson-kootenay-lake",
    category: "Buyer Guides",
    title: "Does Speculation Tax Apply in Nelson or Kootenay Lake?",
    dek: "A careful starting point for second-home buyers trying to understand BC speculation and vacancy tax without guessing by region.",
    intent: "For non-local buyers and second-home buyers comparing Nelson, Kootenay Lake, Kaslo, and rural properties.",
    image: "/generated/guide-headers/speculation-vacancy-tax-nelson-kootenay-lake.webp",
    readTime: "5 min read",
    sections: [
      { title: "The tax is location-specific", body: ["BC's speculation and vacancy tax applies only in designated taxable regions. Buyers should check the current provincial map and property address rather than assuming the tax applies everywhere in British Columbia.", "This question comes up often for second-home buyers because the wrong assumption can change how a property feels financially."] },
      { title: "Use matters too", body: ["Tax exposure can depend on ownership, residency, use, rental, exemptions, and reporting obligations. A realtor can help frame the property question, but a buyer should confirm tax treatment with official provincial sources and qualified tax advice."] },
      { title: "Confirm before comparing homes", body: ["Two homes at the same price can have different carrying-cost pictures if one has different tax, insurance, rental, strata, or maintenance realities. Sort the tax question early so the shortlist stays honest."] },
    ],
    checklist: ["Check the official taxable-region map", "Confirm the exact property address", "Ask a tax professional about ownership and exemption questions", "Compare carrying costs after tax questions are clear"],
    questions: ["Is this address in a taxable region?", "Could my ownership or use change the answer?", "What other annual carrying costs should I compare with this tax question?"],
    sources: [{ label: "BC speculation and vacancy tax", href: "https://www2.gov.bc.ca/gov/content/taxes/speculation-vacancy-tax" }, { label: "BC taxable regions", href: "https://www2.gov.bc.ca/gov/content/taxes/speculation-vacancy-tax/how-tax-works/taxable-regions" }],
  },
  {
    slug: "can-you-build-expand-rural-kootenay-property",
    category: "Due Diligence",
    title: "Can You Build or Expand on Rural Kootenay Property?",
    dek: "How to think about zoning, permits, servicing, ALR questions, riparian setbacks, outbuildings, and future use before buying rural land.",
    intent: "For buyers who see future potential in acreage, waterfront, shops, cabins, studios, guest space, or a larger renovation.",
    image: "/generated/guide-headers/building-expanding-rural-kootenay-property.webp",
    readTime: "8 min read",
    sections: [
      { title: "Potential is not permission", body: ["Land can feel flexible because there is space around it, but future use depends on zoning, permits, building code, septic capacity, water, access, environmental constraints, ALR status where applicable, and local authority review.", "The phrase 'room for a shop' is not the same as permission to build one."] },
      { title: "Waterfront and creeks add another layer", body: ["Riparian areas, floodplain questions, slope, erosion, foreshore structures, and water licences can affect where and how work is possible. These questions deserve early review on lake, creek, and river properties."] },
      { title: "Ask before value gets priced in", body: ["If future expansion is part of the reason to buy, verify it before valuing the property as if the expansion is certain. A lawyer, local planner, building official, septic professional, surveyor, and insurer may all have a role depending on the plan."] },
    ],
    checklist: ["Check zoning and permitted uses", "Review ALR, riparian, floodplain, and environmental constraints where relevant", "Confirm septic, water, access, and power capacity", "Ask the local authority which permits would be required"],
    questions: ["Can I legally do what I imagine here?", "What professional needs to verify the plan?", "What would make the project slower, more expensive, or impossible?"],
    sources: [...permitSources, { label: "Agricultural Land Commission", href: "https://www.alc.gov.bc.ca/" }, ...waterSources, ...riskReviewSources],
  },
  {
    slug: "wildfire-flood-insurance-kootenay-property",
    category: "Due Diligence",
    title: "Wildfire, Flood, and Insurance Questions for Kootenay Property",
    dek: "A practical risk-review guide for rural, waterfront, forested, and second-home buyers in the Kootenays.",
    intent: "For cautious buyers who want the setting without ignoring insurance, wildfire, flood, access, and maintenance realities.",
    image: "/generated/guide-headers/wildfire-flood-insurance-kootenay-property.webp",
    readTime: "7 min read",
    sections: [
      { title: "Beautiful settings still need risk review", body: ["Forested privacy, lake access, creeks, slopes, and rural roads are part of the Kootenay appeal. They can also affect wildfire exposure, flood questions, drainage, insurance, access, and annual maintenance.", "Risk review does not mean fear. It means understanding ownership clearly before the property becomes emotional."] },
      { title: "Insurance should be checked early", body: ["Buyers should speak with an insurer before removing conditions, especially on rural, waterfront, older, remote, or heavily treed properties. Insurance availability, coverage, exclusions, premiums, and required mitigation can affect the real cost of ownership."] },
      { title: "Mitigation is part of ownership", body: ["FireSmart work, roof and gutter maintenance, defensible space, drainage, snow load, driveway access, and local emergency planning can all matter. A strong showing plan asks how the property is managed in hard seasons, not only how it looks on a good day."] },
    ],
    checklist: ["Check wildfire and flood context", "Speak with an insurer early", "Review access, drainage, roof, trees, and emergency routes", "Ask what mitigation or maintenance the property already has"],
    questions: ["Can this property be insured on terms I can accept?", "What wildfire, flood, drainage, or access risks should I understand?", "What annual maintenance protects the home and the value?"],
    sources: riskReviewSources,
  },

  {
    slug: "nelson-kootenay-home-carrying-costs",
    category: "Buyer Guides",
    title: "Carrying Costs for Nelson and Kootenay Lake Homes",
    dek: "How to think about property tax, insurance, utilities, snow, lake systems, rural maintenance, and caretaker costs before buying.",
    intent: "For second-home, relocation, waterfront, and acreage buyers who want to understand the real cost of ownership.",
    image: "/generated/guide-headers/nelson-kootenay-home-carrying-costs.webp",
    readTime: "7 min read",
    sections: [
      { title: "The mortgage is not the whole ownership cost", body: ["A Kootenay home can come with ordinary costs and property-specific costs. Property tax, utilities, insurance, maintenance, snow removal, road care, septic, water systems, docks, drainage, tree work, caretaker help, and travel can all shape the annual picture.", "This matters most for second homes, rural properties, waterfront, and homes with outbuildings or private access."] },
      { title: "Remote ownership needs a local plan", body: ["If you are not living in the home full time, someone needs to notice small problems before they become expensive. Heat, alarms, frozen pipes, storm damage, snow load, driveway access, and insurance requirements deserve a plan."] },
      { title: "Compare homes by annual reality", body: ["Two homes at the same purchase price can feel very different after tax, insurance, utilities, access, and maintenance. Carrying-cost clarity makes the shortlist more honest."] },
    ],
    checklist: ["Estimate annual property tax and utilities", "Ask about insurance before removing conditions", "Budget snow, road, dock, septic, water, tree, and caretaker costs", "Compare annual ownership costs, not only purchase price"],
    questions: ["What does this home cost to own in a normal year?", "Who handles the property when I am away?", "Which systems are likely to need specialist maintenance?"],
    sources: [...bcTaxSources, ...riskReviewSources, rdckSource],
  },
  {
    slug: "first-time-home-buyer-nelson-bc",
    category: "Buyer Guides",
    title: "First-Time Home Buyer Guide for Nelson, BC",
    dek: "A simple first step guide to pre-approval, deposits, conditions, inspections, lawyers, costs, and possession day.",
    intent: "For first-time buyers in Nelson or the Kootenays who want the process explained clearly before they start touring.",
    image: "/generated/guide-headers/first-time-home-buyer-nelson-bc.webp",
    readTime: "7 min read",
    sections: [
      { title: "Start with readiness, not listings", body: ["A first search should begin with financing, down payment, monthly comfort, deposit access, and the type of home you can responsibly pursue. Browsing before readiness can make the process louder than it needs to be."] },
      { title: "Understand the steps", body: ["Most buyers move through pre-approval, search, showing, offer, deposit, conditions, inspection, insurance, legal work, and possession. Each step has timing and decisions attached to it."] },
      { title: "Ask early, not when you are rushed", body: ["The best first-time buyer questions are simple: what can I afford, what should I avoid, what costs are coming, and what should I verify before I get attached? A calm start protects the whole process."] },
    ],
    checklist: ["Get mortgage pre-approval", "Confirm deposit funds and closing-cost budget", "Understand subjects and timelines", "Choose a lawyer before you need one"],
    questions: ["What can I afford without stretching too far?", "What costs come after the price?", "Which conditions protect me?"],
    sources: [...buyerProcessSources, ...bcTaxSources],
  },
  {
    slug: "buying-with-conditions-bc-real-estate",
    category: "Buyer Guides",
    title: "Buying With Conditions in BC Real Estate",
    dek: "How buyers should think about financing, inspection, insurance, title, strata, septic, water, and other subjects before writing.",
    intent: "For buyers preparing to write an offer and wanting to understand what must be verified first.",
    image: "/generated/guide-headers/buying-with-conditions-bc-real-estate.webp",
    readTime: "6 min read",
    sections: [
      { title: "Conditions should match the property", body: ["A downtown home, rural acreage, waterfront property, strata home, and older house may need different review. Conditions are not boilerplate. They should reflect what a buyer needs to verify before becoming firm."] },
      { title: "Speed and protection both matter", body: ["A strong offer is not always the shortest offer. It is the offer that fits the property, market, seller, and buyer risk tolerance. The work is knowing what can be checked before writing and what needs a condition."] },
      { title: "Plan professionals before the deadline", body: ["Inspectors, insurers, lawyers, lenders, septic professionals, well specialists, and strata document reviewers may all need time. The condition period should be realistic for the property."] },
    ],
    checklist: ["Identify must-check items before writing", "Confirm financing and insurance timing", "Match conditions to the property type", "Book professionals early"],
    questions: ["What must be verified before I can go firm?", "Which conditions are standard and which are property-specific?", "Can any work be done before offer day?"],
    sources: [...buyerProcessSources, ...inspectionSources, ...ltsaSources],
  },
  {
    slug: "home-inspection-rural-waterfront-kootenays",
    category: "Due Diligence",
    title: "Home Inspection Guide for Rural and Waterfront Property",
    dek: "What standard inspections may miss and when to bring in septic, well, roof, structural, insurance, or waterfront specialists.",
    intent: "For buyers considering homes where systems, water, slope, access, or age make the inspection more important.",
    image: "/generated/guide-headers/home-inspection-rural-waterfront-kootenays.webp",
    readTime: "7 min read",
    sections: [
      { title: "A normal inspection may not be enough", body: ["General home inspections are useful, but rural and waterfront properties can involve extra systems and site questions. Septic, water, wells, drainage, docks, roofs, retaining walls, access, outbuildings, and insurance may need separate review."] },
      { title: "Specialists answer specialist questions", body: ["A good inspection plan asks who is qualified to answer each risk. A home inspector, septic professional, well specialist, structural engineer, roofer, insurer, and local authority may all have different roles."] },
      { title: "Use the inspection to decide, not negotiate blindly", body: ["Inspection findings should help the buyer understand ownership, timing, repair risk, insurance, and whether the property still fits. Not every issue is fatal, but hidden systems should not be ignored."] },
    ],
    checklist: ["Book a licensed home inspector", "Decide if septic, well, roof, structural, or dock review is needed", "Ask the insurer about property-specific issues", "Review inspection findings against price and ownership plans"],
    questions: ["What does a normal inspection not cover here?", "Which systems need specialist review?", "Would any finding change my offer, insurance, or maintenance plan?"],
    sources: [...inspectionSources, ...waterSources, ...riskReviewSources],
  },
  {
    slug: "title-easements-rights-of-way-rural-bc",
    category: "Due Diligence",
    title: "Title, Easements, and Rights-of-Way in Rural BC",
    dek: "A guide to shared roads, utility access, lake paths, covenants, title documents, and the legal rights that can shape rural ownership.",
    intent: "For buyers who need to understand access and legal rights before trusting what a property appears to offer.",
    image: "/generated/guide-headers/title-easements-rights-of-way-rural-bc.webp",
    readTime: "7 min read",
    sections: [
      { title: "Physical access is not the same as legal access", body: ["A driveway, lake path, road, gate, or utility route may look simple at a showing. The title and supporting documents explain what rights and obligations actually exist."] },
      { title: "Shared roads need clear responsibilities", body: ["If access depends on a shared road, easement, right-of-way, strata road, or informal neighbour arrangement, understand who maintains it, who pays, who plows, and what happens when repairs are needed."] },
      { title: "Let the lawyer review the documents", body: ["Title documents, charges, covenants, easements, rights-of-way, and plans should be reviewed by a lawyer. A realtor can help identify questions early, but legal interpretation belongs with legal counsel."] },
    ],
    checklist: ["Order and review title documents", "Ask about easements, covenants, and rights-of-way", "Confirm road, utility, and lake-access responsibilities", "Have a lawyer review documents before going firm"],
    questions: ["Do I have legal access to everything I expect to use?", "Who pays for shared roads or utilities?", "Are there covenants or charges that limit future use?"],
    sources: [...ltsaSources, rdckSource],
  },
  {
    slug: "alr-agricultural-land-kootenays",
    category: "Due Diligence",
    title: "ALR and Agricultural Land in the Kootenays",
    dek: "What buyers should understand about Agricultural Land Reserve properties, permitted uses, restrictions, and future plans before buying acreage.",
    intent: "For acreage buyers looking at pasture, farms, rural estates, and properties with agricultural potential or restrictions.",
    image: "/generated/guide-headers/alr-agricultural-land-kootenays.webp",
    readTime: "6 min read",
    sections: [
      { title: "ALR can affect what land can become", body: ["Agricultural Land Reserve status can shape subdivision, non-farm uses, dwellings, soil, and long-term plans. Buyers should not assume rural land can be used however they want because it is large or private."] },
      { title: "Maps and rules come first", body: ["Before pricing future potential into a property, check whether the land is in the ALR and what local zoning also says. ALC rules and local government rules can both matter."] },
      { title: "Farm potential and estate potential are different", body: ["Some buyers want productive land. Others want privacy and space. Those goals can overlap, but they are not the same. The ownership plan should fit the rules and the land itself."] },
    ],
    checklist: ["Check ALR status", "Review local zoning", "Confirm permitted dwellings, structures, and uses", "Get advice before assuming subdivision or non-farm use"],
    questions: ["Is this property in the ALR?", "What uses are permitted?", "Could my future plan require approval?"],
    sources: [...alrSources, ...permitSources],
  },
  {
    slug: "remote-buying-kootenay-property",
    category: "Buyer Guides",
    title: "Remote Buying Guide for Kootenay Property",
    dek: "How out-of-town buyers can use video, local scouting, document review, inspections, and travel timing without rushing a major decision.",
    intent: "For Vancouver, Calgary, Ontario, US, and international buyers trying to evaluate Kootenay homes from a distance.",
    image: "/generated/guide-headers/remote-buying-kootenay-property.webp",
    readTime: "6 min read",
    sections: [
      { title: "Remote buying needs a better filter", body: ["Photos are not enough when roads, slope, sun, privacy, lake access, noise, and winter all matter. A remote buyer needs a clear scouting process before spending time and money travelling."] },
      { title: "Video should answer practical questions", body: ["A useful remote preview should show approach, road, driveway, neighbours, grade, water access, mechanical areas, storage, internet context, and anything the listing photos avoid."] },
      { title: "Do not compress due diligence", body: ["Distance can create pressure to move quickly. The answer is preparation: financing, lawyer, inspector, insurance, document review, and local questions lined up before the right property appears."] },
    ],
    checklist: ["Define must-have daily-life fit before touring remotely", "Ask for practical video, not only beauty shots", "Line up lawyer, lender, inspector, and insurer early", "Plan travel around serious contenders"],
    questions: ["What can I trust from photos and what needs local eyes?", "Which properties deserve a trip?", "How do we keep speed without skipping review?"],
    sources: [...buyerProcessSources, ...ltsaSources],
  },
  {
    slug: "downsizing-nelson-kootenay-lake",
    category: "Seller Guides",
    title: "Downsizing in Nelson or Kootenay Lake",
    dek: "A guide for owners moving from a larger home, acreage, or waterfront property into a simpler next chapter.",
    intent: "For sellers who want less maintenance, more convenience, or a different daily rhythm without rushing the decision.",
    image: "/generated/guide-headers/downsizing-nelson-kootenay-lake.webp",
    readTime: "6 min read",
    sections: [
      { title: "Downsizing is usually about life, not square footage", body: ["Many owners are not just selling space. They are changing maintenance, stairs, snow, access, gardens, guest needs, travel, and how close they want to be to services or family."] },
      { title: "The sale and next purchase should work together", body: ["A good plan considers timing, market preparation, where you will go next, what needs to be handled privately, and how to avoid being rushed by either side of the move."] },
      { title: "The home still deserves a strong presentation", body: ["A long-held home, acreage, or waterfront property should be prepared with care. The story should help the next buyer understand the setting, upkeep, improvements, and daily life."] },
    ],
    checklist: ["Decide what daily life should get easier", "Plan sale timing and next-home timing together", "Prepare documents and maintenance history", "Choose what to handle before photography and showings"],
    questions: ["What am I trying to simplify?", "Should I buy first, sell first, or prepare both paths?", "What will help buyers understand the value of this home?"],
    sources: [{ label: "BC home buying and selling", href: "https://www2.gov.bc.ca/gov/content/housing-tenancy/buying-selling" }, ...localSources],
  },
  {
    slug: "estate-legacy-property-sale-kootenays",
    category: "Seller Guides",
    title: "Selling an Estate or Legacy Property in the Kootenays",
    dek: "How families can approach privacy, preparation, documents, timing, multiple decision-makers, and a respectful sale plan.",
    intent: "For families handling inherited, long-held, waterfront, acreage, or emotionally important properties.",
    image: "/generated/guide-headers/estate-legacy-property-sale-kootenays.webp",
    readTime: "7 min read",
    sections: [
      { title: "Legacy sales need patience and structure", body: ["A long-held property can carry family history, deferred decisions, incomplete documents, and multiple voices. The sale plan should create clarity before the property reaches the market."] },
      { title: "Documents reduce stress", body: ["Useful preparation can include title, surveys or plans if available, permits, maintenance records, utility information, water and septic records, rental history, and any family decisions about timing or privacy."] },
      { title: "Presentation should respect the property", body: ["A legacy property should not be rushed into generic marketing. Buyers need to understand what is special, what needs work, and how the property could live for the next owner."] },
    ],
    checklist: ["Clarify decision-makers and timing", "Gather title, plans, permits, and maintenance records", "Decide privacy and showing boundaries", "Prepare the property story before pricing"],
    questions: ["Who needs to approve decisions?", "What documents are missing?", "How do we honour the property while still selling clearly?"],
    sources: [...ltsaSources, { label: "BC home buying and selling", href: "https://www2.gov.bc.ca/gov/content/housing-tenancy/buying-selling" }],
  },
  {
    slug: "when-to-sell-waterfront-acreage-kootenays",
    category: "Seller Guides",
    title: "When to Sell Waterfront or Acreage in the Kootenays",
    dek: "How seasonality, photography, lake access, snow, buyer travel, and preparation affect the timing of an important listing.",
    intent: "For sellers deciding when to bring a waterfront, acreage, or unique Kootenay property to market.",
    image: "/generated/guide-headers/when-to-sell-waterfront-acreage-kootenays.webp",
    readTime: "6 min read",
    sections: [
      { title: "Timing should show the property honestly", body: ["Some homes photograph best when gardens, water, docks, approach, and outdoor rooms are visible. Others need winter context because access, heat, and snow are part of the ownership story."] },
      { title: "Preparation can matter more than the month", body: ["A rushed listing in the right season can still underperform. Documents, cleanup, repairs, photography, film, pricing, and buyer targeting should be ready before launch."] },
      { title: "Buyer travel shapes showing quality", body: ["Waterfront, acreage, and second-home buyers may need time to travel. A good sale plan respects that timing and builds enough clarity online to make showings serious."] },
    ],
    checklist: ["Choose the season that shows the property's strengths", "Prepare documents before photography", "Plan photography and film around weather and access", "Give serious buyers enough information to travel"],
    questions: ["What season shows this property best?", "What should be ready before we list?", "Which buyers need time to plan a showing?"],
    sources: [...localSources, ...riskReviewSources],
  },

  {
    slug: "best-areas-to-live-nelson-bc",
    category: "Buyer Guides",
    title: "Best Areas to Live in Nelson, BC",
    dek: "A plain guide to Nelson neighbourhoods, North Shore, Balfour, Blewett, and nearby Kootenay communities by daily life, access, sun, schools, lake, and winter routine.",
    intent: "For buyers searching Nelson BC real estate and trying to choose the right area before booking showings.",
    image: "/generated/guide-headers/best-areas-to-live-nelson-bc.webp",
    readTime: "8 min read",
    sections: [
      { title: "Start with the life you want", body: ["There is no single best area for every Nelson buyer. A walkable Baker Street life, a quiet lake-view home, North Shore privacy, Blewett acreage, Balfour ferry rhythm, and Kaslo village life all solve different problems.", "The better question is which area matches your daily routine: work, school, errands, winter driving, trail access, lake use, guests, and how much maintenance you want around the home."] },
      { title: "Nelson neighbourhoods feel different street by street", body: ["Fairview often attracts buyers who want lake access, parks, schools, and a flatter routine. Uphill can offer heritage character, sun, and walkability, but slope and parking matter. Rosemont, Granite Pointe, and view streets can suit buyers who want space, outlook, and quieter surroundings while staying close to town.", "The right choice depends on the exact street, grade, sun, parking, snow, and how often you want to walk versus drive."] },
      { title: "Nearby communities widen the search", body: ["North Shore, Balfour, Blewett, Procter, Harrop, Kaslo, and rural pockets around Nelson can offer more privacy, lake access, acreage, shops, gardens, or quieter living. They also add questions about winter access, services, wells, septic, internet, and how often you want to be in town."] },
      { title: "Use showings to test the routine", body: ["A smart area tour is not only a property tour. Drive the school route, grocery route, winter approach, guest arrival, lake access, commute, and evening return. The home is only right if the area works when the novelty wears off."] },
    ],
    checklist: ["Decide walkability, lake, view, acreage, or quiet first", "Compare winter access, parking, sun, and slope", "Tour daily routes, not only homes", "Ask Luke which tradeoffs buyers notice after moving"],
    questions: ["Which Nelson area fits my actual daily life?", "What will winter, slope, or access change?", "Should I stay in town or widen the search to nearby communities?"],
    sources: [{ label: "Nelson area guide", href: "/nelson" }, ...localSources, rdckSource],
  },
  {
    slug: "kootenay-lake-real-estate-market-guide",
    category: "Buyer Guides",
    title: "Kootenay Lake Real Estate Market Guide",
    dek: "How buyers and sellers should read the Kootenay Lake market without relying on stale averages or broad provincial headlines.",
    intent: "For buyers and sellers comparing Kootenay Lake waterfront, lake access, view, acreage, and nearby town properties.",
    image: "/generated/guide-headers/kootenay-lake-real-estate-market-guide.webp",
    readTime: "7 min read",
    sections: [
      { title: "Kootenay Lake is not one market", body: ["Waterfront, shared lake access, lake view, in-town Nelson homes, Balfour properties, Kaslo-area homes, acreage, and rural land can move differently. A single market average can hide the details that decide value.", "The useful comparison is the property type, rights, condition, access, setting, and buyer depth around the specific home."] },
      { title: "Current competition matters more than old headlines", body: ["A market guide should help you frame the questions, not pretend that one permanent number applies. Active listings, recent comparable sales, days on market, price changes, property condition, seasonality, and whether a home has a clear buyer all matter."] },
      { title: "Unique property needs a better value argument", body: ["Lakefront, acreage, private estates, and long-held homes often need a careful explanation of what is scarce, what is practical, what must be verified, and what buyers will compare against. The strongest pricing and offer decisions are built from evidence, not excitement."] },
    ],
    checklist: ["Separate waterfront, access, view, town, and acreage comparisons", "Review current competition and recent sales", "Check property-specific facts before relying on averages", "Ask for a local read before pricing or offering"],
    questions: ["What is the real comparison set for this property?", "Is the market supporting the price or only the story?", "What should change my offer or sale strategy right now?"],
    sources: [{ label: "Kootenay Lake waterfront real estate", href: "/kootenay-lake-waterfront-real-estate" }, { label: "Luke Mori listings", href: "/listings" }, { label: "Luke Mori sold listings", href: "/listings/sold" }],
  },
  {
    slug: "nelson-bc-luxury-homes-guide",
    category: "Buyer Guides",
    title: "Nelson BC Luxury Homes Guide",
    dek: "What makes an important Nelson home valuable: setting, views, privacy, architecture, access, land, systems, and resale confidence.",
    intent: "For buyers searching Nelson BC luxury homes, lake-view homes, acreage estates, and important Kootenay properties.",
    image: "/generated/guide-headers/nelson-bc-luxury-homes-guide.webp",
    readTime: "7 min read",
    sections: [
      { title: "Luxury is not only finish level", body: ["In Nelson, important homes are often valuable because of setting: Kootenay Lake views, walkability, privacy, sun, architecture, land, guest space, shops, gardens, or rare access. Fine finishes help, but the location and daily life usually carry the value."] },
      { title: "The best homes still need practical review", body: ["A beautiful home can still raise questions about winter access, slope, parking, roof, drainage, heating, insurance, title, zoning, strata, septic, water, or future renovations. Serious buyers should verify the quiet details before emotion takes over."] },
      { title: "Resale confidence comes from clarity", body: ["A strong purchase is easier to defend when the setting, condition, comparable sales, buyer depth, and future use are understood. The more unique the home, the more important the explanation becomes."] },
    ],
    checklist: ["Separate setting value from finish value", "Check access, slope, sun, parking, and systems", "Compare against real alternatives", "Ask which details protect long-term resale"],
    questions: ["Why is this home worth more than the alternatives?", "What risk hides behind the beauty?", "Would the next buyer understand the value as clearly as I do?"],
    sources: [{ label: "Nelson luxury listings", href: "/listings/luxury" }, { label: "Nelson BC realtor", href: "/nelson-bc-realtor" }, ...inspectionSources, ...ltsaSources],
  },
  {
    slug: "selling-luxury-home-nelson-bc",
    category: "Seller Guides",
    title: "Selling a Luxury Home in Nelson, BC",
    dek: "How to prepare, price, explain, and protect the sale of an important Nelson home without turning the process into noise.",
    intent: "For Nelson and Kootenay sellers preparing a view home, waterfront home, acreage property, or long-held family home for market.",
    image: "/generated/guide-headers/selling-luxury-home-nelson-bc.webp",
    readTime: "7 min read",
    sections: [
      { title: "Important homes need a clearer plan", body: ["A strong sale plan starts by defining the likely buyer, the property strengths, the likely objections, the showing plan, privacy needs, and the facts that support value. The goal is not more noise. The goal is the right attention from serious buyers."] },
      { title: "Preparation builds confidence", body: ["Before listing, gather useful documents, service history, upgrade notes, floor and room information, utility context, access details, and anything a careful buyer will ask about. This is especially important for older homes, view properties, acreage, waterfront, and homes with guest space or suites."] },
      { title: "Marketing should explain, not exaggerate", body: ["Photography, film, copy, room information, area context, and private showing strategy should make the property easier to understand. Overheated language cannot replace clear proof, good visuals, and a calm negotiation plan."] },
    ],
    checklist: ["Define the likely buyer and objections", "Prepare documents before photography", "Build a pricing argument from evidence", "Protect privacy while giving serious buyers enough clarity"],
    questions: ["Who is the best buyer for this home?", "What should be fixed, documented, or explained before listing?", "How will the price be defended if the market pushes back?"],
    sources: [{ label: "Luke Mori seller guidance", href: "/sellers" }, { label: "Luke Mori about", href: "/about" }, { label: "Luke Mori sold listings", href: "/listings/sold" }],
  },
  {
    slug: "selling-waterfront-property-kootenay-lake",
    category: "Seller Guides",
    title: "Selling Waterfront Property on Kootenay Lake",
    dek: "How sellers can prepare shoreline, access, documents, systems, privacy, photography, and buyer questions before going to market.",
    intent: "For owners of Kootenay Lake waterfront, lake access, creekside, or view properties preparing to sell.",
    image: "/generated/guide-headers/selling-waterfront-property-kootenay-lake.webp",
    readTime: "7 min read",
    sections: [
      { title: "Waterfront buyers ask sharper questions", body: ["Buyers are not only buying the view. They want to understand access, shoreline usability, privacy, slope, foreshore questions, dock or moorage details, septic, water, insurance, maintenance, and what rights transfer with the property."] },
      { title: "Documents should be ready before attention", body: ["Gather title material, surveys or plans if available, dock or foreshore information, water and septic records, strata or shared-access documents, maintenance history, and any local authority information that may help serious buyers verify the property."] },
      { title: "Show the lake honestly", body: ["Strong waterfront marketing shows approach, stairs or grade, outdoor rooms, shoreline, privacy, parking, guest flow, views, and seasonal use. It should not imply private rights or uses that are not documented."] },
    ],
    checklist: ["Clarify private, shared, licensed, and informal waterfront use", "Prepare water, septic, access, and maintenance records", "Plan photography around light, shoreline, and approach", "Price against the correct waterfront comparison set"],
    questions: ["What exact waterfront rights can be shown and proven?", "What will cautious buyers ask before booking travel?", "Which claims should be avoided because they are not documented?"],
    sources: [...waterSources, ...riskReviewSources, { label: "Kootenay Lake waterfront real estate", href: "/kootenay-lake-waterfront-real-estate" }],
  },


];

export const guideCategories = ["Buyer Guides", "Due Diligence", "Seller Guides"] as const;

export function getGuideBySlug(slug: string): BuyerGuide | undefined {
  return buyerGuides.find((guide) => guide.slug === slug);
}
